branches:
  only:
    - scopeV2
    - main
language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: cd scopeV2 && pytest # run tests
after_success:
  - cd scopeV2 && codecov # submit coverage